apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-console-proxy
  labels:
    vm-console-proxy.kubevirt.io: vm-console-proxy
    name: vm-console-proxy
spec:
  selector:
    matchLabels:
      vm-console-proxy.kubevirt.io: vm-console-proxy
  replicas: 1
  template:
    metadata:
      labels:
        vm-console-proxy.kubevirt.io: vm-console-proxy
        name: vm-console-proxy
    spec:
      serviceAccountName: vm-console-proxy
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /console
          imagePullPolicy: IfNotPresent
          args: []
          image: console:latest
          name: console
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            requests:
              memory: "65Mi"
              cpu: "100m"
          ports:
            - name: http-api
              protocol: TCP
              containerPort: 8768
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /readyz
              port: 8769
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8769
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          volumeMounts:
            - name: "config"
              mountPath: "/config"
              readOnly: true
            - name: "vm-console-proxy-cert"
              mountPath: "/tmp/vm-console-proxy-cert"
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: "config"
          configMap:
            name: "vm-console-proxy"
        - name: "vm-console-proxy-cert"
          secret:
            secretName: "vm-console-proxy-cert"
